apiVersion: apps/v1
kind: Deployment
metadata:
  name: toy
spec:
  selector:
    matchLabels:
      app: toy
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: toy
      labels:
        app: toy
    spec:
      containers:
      - image: chenwei67/toy-error
        name: toy
        readinessProbe:
          periodSeconds: 1
          httGet:
            path: /
            port: 8080
        imagePullPolicy: IfNotPresent